### PR TITLE
Color hint

### PR DESCRIPTION
**Pull request by fitz0019**
Hey,

Great Bracket extension - really useful.

I thought it'll be good to show the color swatch within the auto complete. I'm using 'tinycolor' to check if the value is a valid color and then display it how other auto completes within Brackets show color swatches. I've also changed screenshot1 so you can also see what it looks like.

This is my first pull request so forgive me if I've not got the process quite right.

Thanks,

Fitz

### CODE REVIEW

**Comment by konstantinkobs** [comment]
Hey, looks great! One thing: Could you add TinyColor to the dependencies in `package.json` and put it in the right folder (`node-modules`, I think), so you can install the dependencies with node.js via `npm install`. ;)
Then I will merge this Pull Request. I have a very similar extension for LESS variables. I would like to use your code in this extension, too. :)

**Comment by fitz0019** [comment]
Glad you like it. I will get this done later today.

Once done feel free to reuse it for your LESS extension.

**Comment by fitz0019** [comment]
Just had a look and apparently Brackets doesn't run `npm install` so the dependencies won't be downloaded when a user installed the extension.

I've found a couple of links that indicate that the current way of adding dependencies is to bundle it with the extension:
- https://github.com/adobe/brackets/wiki/Extension-package-format#node-modules
- https://github.com/adobe/brackets/wiki/Brackets-Node-Process:-Overview-for-Developers#step-0-setting-up-the-extension

What do you think? We don't want to add the `node_modules` to the repository.

**Comment by konstantinkobs** [comment]
As [you stated](https://github.com/adobe/brackets/wiki/Brackets-Node-Process:-Overview-for-Developers#step-0-setting-up-the-extension): We should put a `node/node_modules` inside the structure, but put the `node_module` folder inside the `.gitignore`. A `package.json` file should be placed inside the `node` directory. I think, if this is the recommended way of doing this, we should do this. :wink: 

I have to admit, that I thought, we could put the dependency inside the main `package.json` file.

Thank you for your research!

**Comment by fitz0019** [comment]
The 'package.json' method is the recommended way of handling dependencies, but currently Brackets doesn't use it. I've checked a number of Brackets Extensions and none use 'package.json' and put there dependencies in a folder within the repository.

I think it's safe to do accept the pull request and we can revisit when Brackets starts using 'package.json'.

**Comment by konstantinkobs** [comment]
Thanks for your work! I merged it now. :smile:

**Comment by fitz0019** [comment]
No problem, keep up the good work. Already got my work colleagues using it as they thought it was a great idea.

**Pull request merged**
